### ISSUE TITLE
No issues, just saying thank you

### ISSUE THREAD

**Issue by zoalasaurusrawr** [dmarlow/BearerTokenBridge#1]
I've lost days and days trying to find an acceptable way to bridge my old OAuth Bearer code until I can convert to OIDC. This is a lifesaver.

Can I donate somewhere?

**Comment by dmarlow** [comment]
Thanks for reaching out! I'm glad others found it useful. I too spent days and days. If you feel like donating, please donate to a charity of your choosing. :)

I have another repo that I think may be better: https://github.com/dmarlow/AspNetTicketBridge
It has some minor improvements to the API and will make changes/fixes to that new repo. I'll update the main readme here to reflect that.
